'use client';

import { useEffect, useMemo, useRef, useState, useTransition } from 'react';
import { createExpense, deleteExpense, updateExpense } from './actions';
import { toast } from 'sonner';
import { getMoneyDecimals } from '@/lib/money';
import {
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  Legend,
  LineChart,
  Line,
  CartesianGrid,
  PieChart,
  Pie,
  Cell,
  Brush,
} from 'recharts';

type IncomeRow = {
  id: string;
  startIso: string;
  feeCents: number;
  paymentStatus: 'pending' | 'paid' | string;
  patientName?: string | null;
};

type ExpenseRow = {
  id: string;
  date: string; // YYYY-MM-DD
  title: string;
  category?: string | null;
  method?: string | null;
  amountCents: number;
  notes?: string | null;
  recurring: boolean;
  recurringGroup?: string | null;
  recurringDay?: number | null;
  recurringStart?: string | null;
  autoGenerated?: boolean | null;
  createdAt: string;
  updatedAt: string;
};

type Debtor = { patientId: string; patientName: string; amount: number };

function fmtCOP(cents: number) {
  const v = Math.round((cents ?? 0) / 100);
  return new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(v);
}

function toCOPInput(cents: number) {
  return String(Math.round((cents ?? 0) / 100));
}

function parseDateOnly(isoOrDate: string) {
  const s = (isoOrDate ?? '').trim();
  if (!s) return new Date(NaN);
  if (/^\d{4}-\d{2}-\d{2}$/.test(s)) return new Date(`${s}T00:00:00`);
  return new Date(s);
}

function dateKey(d: Date) {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

function startOfISOWeek(d: Date) {
  const day = d.getDay(); // 0 Sun, 1 Mon
  const diff = (day === 0 ? -6 : 1 - day);
  const x = new Date(d);
  x.setDate(d.getDate() + diff);
  x.setHours(0, 0, 0, 0);
  return x;
}

function weekLabel(d: Date) {
  const s = startOfISOWeek(d);
  const e = new Date(s);
  e.setDate(s.getDate() + 6);
  const fmt = (x: Date) => `${String(x.getDate()).padStart(2, '0')}/${String(x.getMonth() + 1).padStart(2, '0')}`;
  return `${fmt(s)}–${fmt(e)}`;
}

function useDebouncedMap(delayMs: number) {
  const timers = useRef(new Map<string, any>());
  return (key: string, fn: () => void) => {
    const cur = timers.current.get(key);
    if (cur) clearTimeout(cur);
    const t = setTimeout(() => {
      timers.current.delete(key);
      fn();
    }, delayMs);
    timers.current.set(key, t);
  };
}

export function FinanceClient({
  monthLabel,
  incomeRows,
  expenseRows,
  debtors,
  totals,
  yearIncomeRows,
  yearExpenseRows,
  yearPatientRows,
}: {
  monthLabel: string;
  incomeRows: IncomeRow[];
  expenseRows: ExpenseRow[];
  debtors: Debtor[];
  totals: { billedCents: number; paidCents: number; pendingCents: number; expenseCents: number; netCents: number };
  yearIncomeRows: Array<{ startIso: string; feeCents: number; paymentStatus: string }>;
  yearExpenseRows: Array<{ date: string; amountCents: number; category?: string | null; title?: string | null }>;
  yearPatientRows: Array<{ startIso: string; patientId: string; status: string; patientName?: string | null }>;
}) {
  const decimals = getMoneyDecimals();
  const [tab, setTab] = useState<'resumen' | 'ingresos' | 'egresos' | 'graficos'>('resumen');
  const [pending, startTransition] = useTransition();

  const [exp, setExp] = useState<ExpenseRow[]>(expenseRows.slice().sort((a, b) => a.date.localeCompare(b.date)));
  useEffect(() => setExp(expenseRows.slice().sort((a, b) => a.date.localeCompare(b.date))), [expenseRows]);

  const debounce = useDebouncedMap(800);

  const [newE, setNewE] = useState({
    date: `${monthLabel}-01`,
    title: '',
    category: '',
    method: '',
    amountCOP: '',
    notes: '',
    recurring: false,
  });

  useEffect(() => {
    setNewE((s) => ({ ...s, date: `${monthLabel}-01` }));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [monthLabel]);

  const seriesDay = useMemo(() => {
    const incomePaid = new Map<string, number>();
    for (const r of incomeRows) {
      if (r.paymentStatus !== 'paid') continue;
      const d = parseDateOnly(r.startIso);
      if (!Number.isFinite(d.getTime())) continue;
      const k = dateKey(d);
      incomePaid.set(k, (incomePaid.get(k) ?? 0) + (r.feeCents ?? 0));
    }
    const expMap = new Map<string, number>();
    for (const r of exp) {
      const d = parseDateOnly(r.date);
      if (!Number.isFinite(d.getTime())) continue;
      const k = dateKey(d);
      expMap.set(k, (expMap.get(k) ?? 0) + (r.amountCents ?? 0));
    }

    const base = new Date(`${monthLabel}-01T00:00:00`);
    const y = base.getFullYear();
    const m = base.getMonth();
    const daysInMonth = new Date(y, m + 1, 0).getDate();
    const out: any[] = [];
    for (let day = 1; day <= daysInMonth; day++) {
      const d = new Date(y, m, day);
      const k = dateKey(d);
      const inc = incomePaid.get(k) ?? 0;
      const ex = expMap.get(k) ?? 0;
      out.push({
        label: String(day).padStart(2, '0'),
        ingresos: Math.round(inc / 100),
        egresos: Math.round(ex / 100),
        utilidad: Math.round((inc - ex) / 100),
      });
    }
    return out;
  }, [incomeRows, exp, monthLabel]);

  const seriesWeek = useMemo(() => {
    const bucket = new Map<string, { ingresos: number; egresos: number; utilidad: number; _order: number }>();

    const add = (d: Date, incCents: number, expCents: number) => {
      const s = startOfISOWeek(d);
      const key = weekLabel(d);
      const order = s.getTime();
      const cur = bucket.get(key) ?? { ingresos: 0, egresos: 0, utilidad: 0, _order: order };
      cur.ingresos += incCents;
      cur.egresos += expCents;
      cur.utilidad += incCents - expCents;
      cur._order = Math.min(cur._order, order);
      bucket.set(key, cur);
    };

    for (const r of incomeRows) {
      if (r.paymentStatus !== 'paid') continue;
      const d = parseDateOnly(r.startIso);
      if (!Number.isFinite(d.getTime())) continue;
      add(d, r.feeCents ?? 0, 0);
    }
    for (const r of exp) {
      const d = parseDateOnly(r.date);
      if (!Number.isFinite(d.getTime())) continue;
      add(d, 0, r.amountCents ?? 0);
    }

    return [...bucket.entries()]
      .map(([label, v]) => ({
        label,
        ingresos: Math.round(v.ingresos / 100),
        egresos: Math.round(v.egresos / 100),
        utilidad: Math.round(v.utilidad / 100),
        _order: v._order,
      }))
      .sort((a, b) => a._order - b._order)
      .map(({ _order, ...rest }) => rest);
  }, [incomeRows, exp]);

  

const baseYear = useMemo(() => {
  const d = new Date(`${monthLabel}-01T00:00:00`);
  return d.getFullYear();
}, [monthLabel]);

const seriesMonth = useMemo(() => {
  const incomeByMonth = new Array(12).fill(0);
  for (const r of yearIncomeRows) {
    if (r.paymentStatus !== 'paid') continue;
    const d = parseDateOnly(r.startIso);
    if (!Number.isFinite(d.getTime())) continue;
    const mi = d.getMonth();
    incomeByMonth[mi] += r.feeCents ?? 0;
  }
  const expByMonth = new Array(12).fill(0);
  for (const r of yearExpenseRows) {
    const d = parseDateOnly(r.date);
    if (!Number.isFinite(d.getTime())) continue;
    const mi = d.getMonth();
    expByMonth[mi] += r.amountCents ?? 0;
  }
  return Array.from({ length: 12 }, (_, i) => {
    const inc = incomeByMonth[i] ?? 0;
    const ex = expByMonth[i] ?? 0;
    return {
      label: `${String(i + 1).padStart(2, '0')}/${String(baseYear)}`,
      ingresos: Math.round(inc / 100),
      egresos: Math.round(ex / 100),
      utilidad: Math.round((inc - ex) / 100),
    };
  });
}, [yearIncomeRows, yearExpenseRows, baseYear]);


const seriesPatientsMonth = useMemo(() => {
  // Count distinct patients (and total sessions) per month, excluding cancelled appointments.
  const patientSets: Array<Set<string>> = Array.from({ length: 12 }, () => new Set<string>());
  const sessionsByMonth = new Array(12).fill(0);

  for (const r of yearPatientRows) {
    if (r.status === 'cancelled') continue;
    const d = parseDateOnly(r.startIso);
    if (!Number.isFinite(d.getTime())) continue;
    const mi = d.getMonth();
    sessionsByMonth[mi] += 1;
    if (r.patientId) patientSets[mi].add(r.patientId);
  }

  return Array.from({ length: 12 }, (_, i) => ({
    label: `${String(i + 1).padStart(2, '0')}/${String(baseYear)}`,
    pacientes: patientSets[i].size,
    sesiones: sessionsByMonth[i],
  }));
}, [yearPatientRows, baseYear]);


  const cancelledByMonth = useMemo(() => {
    const cancelled = new Array(12).fill(0);
    for (const r of yearPatientRows) {
      if (r.status !== 'cancelled') continue;
      const d = parseDateOnly(r.startIso);
      if (!Number.isFinite(d.getTime())) continue;
      cancelled[d.getMonth()] += 1;
    }
    return cancelled.map((v, i) => ({
      label: `${String(i + 1).padStart(2, '0')}/${String(baseYear)}`,
      canceladas: v,
    }));
  }, [yearPatientRows, baseYear]);

  const lastCancelled = useMemo(() => {
    return yearPatientRows
      .filter((r) => r.status === 'cancelled')
      .map((r) => ({
        date: (r.startIso ?? '').slice(0, 10),
        startIso: r.startIso,
        patientName: (r.patientName ?? 'Paciente') as string,
      }))
      .filter((r) => r.date && /^\d{4}-\d{2}-\d{2}$/.test(r.date))
      .sort((a, b) => (b.startIso ?? '').localeCompare(a.startIso ?? ''))
      .slice(0, 12);
  }, [yearPatientRows]);

  const topCancellers = useMemo(() => {
    const map = new Map<string, number>();
    for (const r of yearPatientRows) {
      if (r.status !== 'cancelled') continue;
      const name = (r.patientName ?? 'Paciente').trim() || 'Paciente';
      map.set(name, (map.get(name) ?? 0) + 1);
    }
    return [...map.entries()]
      .map(([name, count]) => ({ name, count }))
      .sort((a, b) => b.count - a.count)
      .slice(0, 8);
  }, [yearPatientRows]);


  // Totals per calendar month (index 0..11) for comparisons.
  const monthTotals = useMemo(() => {
    const out = Array.from({ length: 12 }, (_, i) => ({
      monthIndex: i,
      ingresos: 0,
      egresos: 0,
      utilidad: 0,
    }));

    for (const r of yearIncomeRows) {
      if (r.paymentStatus !== 'paid') continue;
      const d = parseDateOnly(r.startIso);
      if (!Number.isFinite(d.getTime())) continue;
      const mi = d.getMonth();
      out[mi].ingresos += Math.round((r.feeCents ?? 0) / 100);
    }
    for (const r of yearExpenseRows) {
      const d = parseDateOnly(r.date);
      if (!Number.isFinite(d.getTime())) continue;
      const mi = d.getMonth();
      out[mi].egresos += Math.round((r.amountCents ?? 0) / 100);
    }
    for (const m of out) m.utilidad = m.ingresos - m.egresos;
    return out;
  }, [yearIncomeRows, yearExpenseRows]);

const seriesCategories = useMemo(() => {
  const map = new Map<string, number>();
  for (const r of yearExpenseRows) {
    const cat = (r.category ?? '').trim() || 'Sin categoría';
    map.set(cat, (map.get(cat) ?? 0) + (r.amountCents ?? 0));
  }
  return [...map.entries()]
    .map(([name, cents]) => ({ name, value: Math.round(cents / 100) }))
    .sort((a, b) => b.value - a.value)
    .slice(0, 12);
}, [yearExpenseRows]);

const topExpenses = useMemo(() => {
  return yearExpenseRows
    .slice()
    .sort((a, b) => (b.amountCents ?? 0) - (a.amountCents ?? 0))
    .slice(0, 10)
    .map((r) => ({
      title: (r.title ?? '').trim() || 'Gasto',
      category: (r.category ?? '').trim() || 'Sin categoría',
      date: String(r.date).slice(0, 10),
      amountCOP: fmtCOP(r.amountCents ?? 0),
    }));
}, [yearExpenseRows]);
  const [gran, setGran] = useState<'dia' | 'semana' | 'mes'>('dia');

  // Month comparison selectors (same year). Default: current month vs previous month.
  const curMonthIndex = useMemo(() => {
    const m = String(monthLabel).split('-')[1];
    const n = Number(m);
    return Number.isFinite(n) && n >= 1 && n <= 12 ? n - 1 : new Date().getMonth();
  }, [monthLabel]);
  const [cmpA, setCmpA] = useState(() => curMonthIndex);
  const [cmpB, setCmpB] = useState(() => (curMonthIndex + 11) % 12);
  useEffect(() => {
    // When user switches month in the URL, update defaults.
    setCmpA(curMonthIndex);
    setCmpB((curMonthIndex + 11) % 12);
  }, [curMonthIndex]);

  const monthNames = useMemo(
    () => ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
    [],
  );

  const compareData = useMemo(() => {
    const a = monthTotals[cmpA] ?? { ingresos: 0, egresos: 0, utilidad: 0 };
    const b = monthTotals[cmpB] ?? { ingresos: 0, egresos: 0, utilidad: 0 };
    return [
      { metric: 'Ingresos', A: a.ingresos, B: b.ingresos },
      { metric: 'Egresos', A: a.egresos, B: b.egresos },
      { metric: 'Utilidad', A: a.utilidad, B: b.utilidad },
    ];
  }, [monthTotals, cmpA, cmpB]);
  const chartData = gran === 'dia' ? seriesDay : gran === 'semana' ? seriesWeek : seriesMonth;

  const onCreateExpense = () => {
    const payload = { ...newE, amountCOP: newE.amountCOP };
    startTransition(async () => {
      try {
        const res = await createExpense(payload);
        if ((res as any)?.ok) {
          toast.success('Gasto agregado');
          setNewE((s) => ({ ...s, title: '', category: '', method: '', amountCOP: '', notes: '' }));
        } else {
          toast.error('No se pudo agregar el gasto');
        }
      } catch (e: any) {
        toast.error(e?.message ?? 'Error creando gasto');
      }
    });
  };

  const updateLocal = (id: string, patch: Partial<ExpenseRow>) => {
    setExp((rows) => rows.map((r) => (r.id === id ? ({ ...r, ...patch } as any) : r)));
    debounce(id, () => {
      const row = exp.find((x) => x.id === id);
      const merged = { ...(row as any), ...(patch as any) };
      startTransition(async () => {
        try {
          await updateExpense({
            id,
            date: merged.date,
            title: merged.title,
            category: merged.category ?? '',
            method: merged.method ?? '',
            amountCOP: toCOPInput(merged.amountCents ?? 0),
            notes: merged.notes ?? '',
            recurring: merged.recurring,
          });
        } catch (e: any) {
          toast.error(e?.message ?? 'Error guardando (autosave)');
        }
      });
    });
  };

  const onDelete = (id: string) => {
    startTransition(async () => {
      try {
        await deleteExpense(id);
        toast.success('Gasto eliminado');
      } catch (e: any) {
        toast.error(e?.message ?? 'Error eliminando gasto');
      }
    });
  };

  return (
    <div className="mt-6">
      <div className="flex flex-wrap gap-2">
        <Tab active={tab === 'resumen'} onClick={() => setTab('resumen')}>Resumen</Tab>
        <Tab active={tab === 'ingresos'} onClick={() => setTab('ingresos')}>Ingresos</Tab>
        <Tab active={tab === 'egresos'} onClick={() => setTab('egresos')}>Egresos (Gastos)</Tab>
        <Tab active={tab === 'graficos'} onClick={() => setTab('graficos')}>Gráficos</Tab>
        <div className="ml-auto text-xs text-slate-500 dark:text-slate-300 flex items-center gap-2">
          {pending ? (
            <span className="px-2 py-1 rounded-lg bg-amber-50 dark:bg-amber-950/30 text-amber-800 dark:text-amber-200">Guardando…</span>
          ) : (
            <span className="px-2 py-1 rounded-lg bg-emerald-50 dark:bg-emerald-950/30 text-emerald-700 dark:text-emerald-200">Todo guardado</span>
          )}
        </div>
      </div>

      {tab === 'resumen' && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mt-6">
          <Card title={`Deudores (${debtors.length})`} subtitle="Pacientes con pagos pendientes en el mes seleccionado.">
            <div className="overflow-auto max-h-[420px]">
              <table className="min-w-full text-sm">
                <thead className="sticky top-0 bg-slate-50 dark:bg-slate-950 border-b border-slate-200 dark:border-slate-800">
                  <tr>
                    <th className="text-left px-3 py-2 font-bold text-slate-600 dark:text-slate-200 min-w-[220px]">Paciente</th>
                    <th className="text-left px-3 py-2 font-bold text-slate-600 dark:text-slate-200 min-w-[160px]">Debe</th>
                    <th className="text-left px-3 py-2 font-bold text-slate-600 dark:text-slate-200 min-w-[120px]">Acción</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                  {debtors.map((d) => (
                    <tr key={d.patientId} className="hover:bg-slate-50 dark:hover:bg-slate-950/50">
                      <td className="px-3 py-2 text-slate-700 dark:text-slate-200">{d.patientName}</td>
                      <td className="px-3 py-2 font-semibold text-slate-800 dark:text-slate-100">{fmtCOP(d.amount)}</td>
                      <td className="px-3 py-2">
                        <a href={`/patient/${d.patientId}`} className="text-xs font-semibold px-2.5 py-1 rounded-lg border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-900">Abrir</a>
                      </td>
                    </tr>
                  ))}
                  {!debtors.length && (
                    <tr><td className="px-3 py-6 text-slate-500 dark:text-slate-300" colSpan={3}>Sin deudores en este mes.</td></tr>
                  )}
                </tbody>
              </table>
            </div>
          </Card>

          <Card title="Utilidad real" subtitle="Lo que realmente ganas: ingresos cobrados − egresos.">
            <div className="space-y-3">
              <Row label="Ingresos cobrados" value={fmtCOP(totals.paidCents)} />
              <Row label="Egresos" value={fmtCOP(totals.expenseCents)} />
              <div className="h-px bg-slate-200 dark:bg-slate-800 my-2" />
              <Row label="Utilidad" value={fmtCOP(totals.netCents)} strong />
              <div className="text-xs text-slate-500 dark:text-slate-300">
                Tip: registra TODO gasto (arriendo, internet, publicidad, apps, comisiones) para ver tu ganancia real.
              </div>
            </div>
          </Card>
        </div>
      )}

      {tab === 'ingresos' && <IncomeTable rows={incomeRows} />}

      {tab === 'egresos' && (
        <div className="grid grid-cols-1 xl:grid-cols-2 gap-6 mt-6">
          <Card title="Agregar gasto" subtitle="Gasto libre: escribe en qué fue y cuánto. Puedes registrar varios.">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              <Field label="Fecha">
                <input type="date" value={newE.date} onChange={(e) => setNewE((s) => ({ ...s, date: e.target.value }))} className="pc-input" />
              </Field>
              <Field label="Valor (COP)">
                <input inputMode="numeric" placeholder="Ej: 50000" value={newE.amountCOP} onChange={(e) => setNewE((s) => ({ ...s, amountCOP: e.target.value }))} className="pc-input" />
              </Field>
              <Field label="¿En qué fue? (texto libre)" full>
                <input placeholder="Ej: Arriendo consultorio / Internet / Publicidad" value={newE.title} onChange={(e) => setNewE((s) => ({ ...s, title: e.target.value }))} className="pc-input" />
              </Field>
              <Field label="Categoría (opcional)">
                <input placeholder="Ej: Fijo / Variable / Marketing" value={newE.category} onChange={(e) => setNewE((s) => ({ ...s, category: e.target.value }))} className="pc-input" />
              </Field>
              <Field label="Método (opcional)">
                <input placeholder="Ej: Transferencia / Efectivo" value={newE.method} onChange={(e) => setNewE((s) => ({ ...s, method: e.target.value }))} className="pc-input" />
              </Field>
              <Field label="Notas (opcional)" full>
                <textarea rows={3} placeholder="Notas…" value={newE.notes} onChange={(e) => setNewE((s) => ({ ...s, notes: e.target.value }))} className="pc-input" />
              </Field>
              <label className="flex items-center gap-2 text-sm text-slate-700 dark:text-slate-200">
                <input type="checkbox" checked={newE.recurring} onChange={(e) => setNewE((s) => ({ ...s, recurring: e.target.checked }))} />
                Es recurrente / fijo
              </label>
              <div className="md:col-span-2 flex justify-end">
                <button onClick={onCreateExpense} disabled={!newE.title.trim() || !newE.amountCOP.trim()} className="px-4 py-2 rounded-xl bg-blue-600 text-white font-semibold hover:bg-blue-700 disabled:opacity-50">+ Agregar</button>
              </div>
            </div>
          </Card>

          <Card title={`Gastos del mes (${exp.length})`} subtitle="Editable con autoguardado (se guarda solo al dejar de escribir).">
            <div className="overflow-auto max-h-[520px]">
              <table className="min-w-full text-sm">
                <thead className="sticky top-0 bg-slate-50 dark:bg-slate-950 border-b border-slate-200 dark:border-slate-800">
                  <tr>
                    <th className="text-left px-3 py-2 font-bold text-slate-600 dark:text-slate-200 min-w-[140px]">Fecha</th>
                    <th className="text-left px-3 py-2 font-bold text-slate-600 dark:text-slate-200 min-w-[260px]">Gasto</th>
                    <th className="text-left px-3 py-2 font-bold text-slate-600 dark:text-slate-200 min-w-[160px]">Categoría</th>
                    <th className="text-left px-3 py-2 font-bold text-slate-600 dark:text-slate-200 min-w-[160px]">Método</th>
                    <th className="text-left px-3 py-2 font-bold text-slate-600 dark:text-slate-200 min-w-[150px]">Valor</th>
                    <th className="text-left px-3 py-2 font-bold text-slate-600 dark:text-slate-200 min-w-[110px]">Acción</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                  {exp.map((r) => (
                    <tr key={r.id} className="hover:bg-slate-50 dark:hover:bg-slate-950/50">
                      <td className="px-3 py-2">
                        <input type="date" value={r.date.slice(0, 10)} onChange={(e) => updateLocal(r.id, { date: e.target.value })} className="pc-input-sm w-[140px]" />
                      </td>
                      <td className="px-3 py-2">
                        <input value={r.title ?? ''} onChange={(e) => updateLocal(r.id, { title: e.target.value })} className="pc-input-sm w-[260px]" />
                      </td>
                      <td className="px-3 py-2">
                        <input value={r.category ?? ''} onChange={(e) => updateLocal(r.id, { category: e.target.value })} className="pc-input-sm w-[160px]" />
                      </td>
                      <td className="px-3 py-2">
                        <input value={r.method ?? ''} onChange={(e) => updateLocal(r.id, { method: e.target.value })} className="pc-input-sm w-[160px]" />
                      </td>
                      <td className="px-3 py-2">
                        <input
                          inputMode="numeric"
                          value={toCOPInput(r.amountCents ?? 0)}
                          onChange={(e) => updateLocal(r.id, { amountCents: Number(String(e.target.value).replace(/\./g, '').replace(/,/g, '')) * 100 })}
                          className="pc-input-sm w-[140px] text-right"
                        />
                      </td>
                      <td className="px-3 py-2">
                        <button onClick={() => onDelete(r.id)} className="text-xs font-semibold px-2.5 py-1 rounded-lg border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-900">Eliminar</button>
                      </td>
                    </tr>
                  ))}
                  {!exp.length && (
                    <tr><td className="px-3 py-8 text-slate-500 dark:text-slate-300" colSpan={6}>No hay gastos en este mes.</td></tr>
                  )}
                </tbody>
              </table>
            </div>
          </Card>
        </div>
      )}

      
{tab === 'graficos' && (
  <div className="grid grid-cols-1 xl:grid-cols-2 gap-6 mt-6">
    <Card title="Ingresos vs Egresos" subtitle="Analiza tu flujo por día, semana o por mes (año completo).">
      <div className="flex items-center gap-2 mb-3">
        <label className="text-xs font-semibold text-slate-600 dark:text-slate-300">Vista</label>
        <select value={gran} onChange={(e) => setGran(e.target.value as any)} className="pc-input-sm">
          <option value="dia">Día (mes actual)</option>
          <option value="semana">Semana (mes actual)</option>
          <option value="mes">Mes (año {baseYear})</option>
        </select>
      </div>
      <div className="h-[320px]">
        <ResponsiveContainer width="100%" height="100%">
          <BarChart data={chartData}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="label" />
            <YAxis />
            <Tooltip formatter={(v: any) => new Intl.NumberFormat('es-CO').format(Number(v))} />
            <Legend />
            <Bar dataKey="ingresos" name="Ingresos" />
            <Bar dataKey="egresos" name="Egresos" />
          </BarChart>
        </ResponsiveContainer>
      </div>
    </Card>

    <Card title="Utilidad" subtitle="Línea de utilidad (ingresos - egresos) para detectar rachas buenas o flojas.">
      <div className="h-[320px]">
        <ResponsiveContainer width="100%" height="100%">
          <LineChart data={chartData}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="label" />
            <YAxis />
            <Tooltip formatter={(v: any) => new Intl.NumberFormat('es-CO').format(Number(v))} />
            <Legend />
            <Line type="monotone" dataKey="utilidad" name="Utilidad" />
          </LineChart>
        </ResponsiveContainer>
      </div>
      <div className="mt-3 text-xs text-slate-500 dark:text-slate-300">Valores en COP (sin decimales).</div>
    </Card>

    <Card title="Comparar meses" subtitle={`Compara dos meses del año ${baseYear}: ingresos, egresos y utilidad.`}>
      <div className="flex flex-wrap items-end gap-3 mb-3">
        <div>
          <div className="text-xs font-semibold text-slate-600 dark:text-slate-300">Mes A</div>
          <select value={cmpA} onChange={(e) => setCmpA(Number(e.target.value))} className="pc-input-sm">
            {monthNames.map((n, i) => (
              <option key={i} value={i}>{n}</option>
            ))}
          </select>
        </div>
        <div>
          <div className="text-xs font-semibold text-slate-600 dark:text-slate-300">Mes B</div>
          <select value={cmpB} onChange={(e) => setCmpB(Number(e.target.value))} className="pc-input-sm">
            {monthNames.map((n, i) => (
              <option key={i} value={i}>{n}</option>
            ))}
          </select>
        </div>
        <div className="text-xs text-slate-500 dark:text-slate-300 ml-auto">
          A = {monthNames[cmpA]} / B = {monthNames[cmpB]}
        </div>
      </div>
      <div className="h-[320px]">
        <ResponsiveContainer width="100%" height="100%">
          <BarChart data={compareData} layout="vertical" margin={{ left: 24, right: 24 }}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis type="number" />
            <YAxis type="category" dataKey="metric" width={90} />
            <Tooltip formatter={(v: any) => new Intl.NumberFormat('es-CO').format(Number(v))} />
            <Legend />
            <Bar dataKey="A" name={`Mes A (${monthNames[cmpA]})`} />
            <Bar dataKey="B" name={`Mes B (${monthNames[cmpB]})`} />
          </BarChart>
        </ResponsiveContainer>
      </div>
      <div className="mt-2 text-xs text-slate-500 dark:text-slate-300">Valores en COP (sin decimales).</div>
    </Card>


    <Card title="Pacientes y sesiones por mes" subtitle={`Indicadores de actividad clínica del año ${baseYear}.`}>
      <div className="overflow-x-auto">
        <div className="h-[320px] min-w-[920px]">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={seriesPatientsMonth} margin={{ left: 8, right: 8 }}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="label" interval={0} tickMargin={8} />
              <YAxis allowDecimals={false} />
              <Tooltip formatter={(v: any) => new Intl.NumberFormat('es-CO').format(Number(v))} />
              <Legend />
              <Bar dataKey="pacientes" name="Pacientes únicos" />
              <Bar dataKey="sesiones" name="Sesiones" />
              <Brush dataKey="label" height={18} travellerWidth={12} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>
      <div className="mt-2 text-xs text-slate-500 dark:text-slate-300">
        *Pacientes = conteo único mensual. Sesiones = citas registradas (excluye canceladas).
      </div>
    </Card>

    <Card title="Cancelaciones" subtitle={`Resumen de citas canceladas en ${baseYear}.`}>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <div className="overflow-x-auto">
          <div className="h-[280px] min-w-[920px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={cancelledByMonth} margin={{ left: 8, right: 8 }}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="label" interval={0} tickMargin={8} />
                <YAxis allowDecimals={false} />
                <Tooltip />
                <Legend />
                <Bar dataKey="canceladas" name="Citas canceladas" />
                <Brush dataKey="label" height={18} travellerWidth={12} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div>
          <div className="text-sm font-bold text-slate-700 dark:text-slate-200 mb-2">Últimas cancelaciones</div>
          <div className="overflow-auto max-h-[240px] border border-slate-200 dark:border-slate-800 rounded-xl">
            <table className="min-w-full text-sm">
              <thead className="sticky top-0 bg-slate-50 dark:bg-slate-950 border-b border-slate-200 dark:border-slate-800">
                <tr>
                  <th className="text-left px-3 py-2 font-bold text-slate-600 dark:text-slate-200 min-w-[110px]">Fecha</th>
                  <th className="text-left px-3 py-2 font-bold text-slate-600 dark:text-slate-200">Paciente</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                {lastCancelled.map((r, i) => (
                  <tr key={i} className="hover:bg-slate-50 dark:hover:bg-slate-950/50">
                    <td className="px-3 py-2 text-slate-700 dark:text-slate-200">{r.date}</td>
                    <td className="px-3 py-2 text-slate-700 dark:text-slate-200">{r.patientName}</td>
                  </tr>
                ))}
                {!lastCancelled.length && (
                  <tr><td className="px-3 py-6 text-slate-500 dark:text-slate-300" colSpan={2}>No hay cancelaciones registradas.</td></tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="mt-3 text-sm font-bold text-slate-700 dark:text-slate-200">Pacientes con más cancelaciones</div>
          <div className="mt-2 grid grid-cols-1 sm:grid-cols-2 gap-2">
            {topCancellers.map((x, i) => (
              <div key={i} className="px-3 py-2 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-950">
                <div className="text-xs font-semibold text-slate-500 dark:text-slate-300">{x.name}</div>
                <div className="text-lg font-extrabold text-slate-900 dark:text-slate-100">{x.count}</div>
              </div>
            ))}
            {!topCancellers.length && (
              <div className="text-xs text-slate-500 dark:text-slate-300">Sin datos todavía.</div>
            )}
          </div>
        </div>
      </div>
    </Card>

    <Card title="Gastos por categoría" subtitle={`Distribución de egresos por categoría (año ${baseYear}).`}>
      <div className="h-[320px]">
        <ResponsiveContainer width="100%" height="100%">
          <PieChart>
            <Tooltip formatter={(v: any) => new Intl.NumberFormat('es-CO').format(Number(v))} />
            <Legend />
            <Pie dataKey="value" nameKey="name" data={seriesCategories} outerRadius={110} label>
              {seriesCategories.map((_, i) => (
                <Cell key={i} />
              ))}
            </Pie>
          </PieChart>
        </ResponsiveContainer>
      </div>
      {!seriesCategories.length ? (
        <div className="text-xs text-slate-500 dark:text-slate-300 mt-2">Aún no hay gastos registrados para este año.</div>
      ) : null}
    </Card>

    <Card title="Top gastos" subtitle={`Los 10 egresos más altos del año ${baseYear}.`}>
      <div className="overflow-auto max-h-[360px]">
        <table className="min-w-full text-sm">
          <thead className="sticky top-0 bg-slate-50 dark:bg-slate-950 border-b border-slate-200 dark:border-slate-800">
            <tr>
              <th className="text-left px-3 py-2 font-bold text-slate-600 dark:text-slate-200 min-w-[110px]">Fecha</th>
              <th className="text-left px-3 py-2 font-bold text-slate-600 dark:text-slate-200 min-w-[220px]">Gasto</th>
              <th className="text-left px-3 py-2 font-bold text-slate-600 dark:text-slate-200 min-w-[160px]">Categoría</th>
              <th className="text-left px-3 py-2 font-bold text-slate-600 dark:text-slate-200 min-w-[140px]">Valor</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
            {topExpenses.map((r, idx) => (
              <tr key={idx} className="hover:bg-slate-50 dark:hover:bg-slate-950/50">
                <td className="px-3 py-2 text-slate-700 dark:text-slate-200">{r.date}</td>
                <td className="px-3 py-2 text-slate-700 dark:text-slate-200">{r.title}</td>
                <td className="px-3 py-2 text-slate-700 dark:text-slate-200">{r.category}</td>
                <td className="px-3 py-2 font-semibold text-slate-900 dark:text-slate-100">{r.amountCOP}</td>
              </tr>
            ))}
            {!topExpenses.length && (
              <tr><td className="px-3 py-6 text-slate-500 dark:text-slate-300" colSpan={4}>Sin datos todavía.</td></tr>
            )}
          </tbody>
        </table>
      </div>
    </Card>
  </div>
)}
    </div>
  );
}

function Tab({ active, children, onClick }: { active: boolean; children: React.ReactNode; onClick: () => void }) {
  return (
    <button
      onClick={onClick}
      className={`px-4 py-2 rounded-xl text-sm font-semibold border ${
        active
          ? 'bg-blue-600 text-white border-blue-600'
          : 'bg-white dark:bg-slate-950 text-slate-700 dark:text-slate-200 border-slate-200 dark:border-slate-800 hover:bg-slate-50 dark:hover:bg-slate-900'
      }`}
    >
      {children}
    </button>
  );
}

function Card({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) {
  return (
    <div className="pc-card bg-white dark:bg-slate-950">
      <h2 className="font-bold text-slate-800 dark:text-slate-100">{title}</h2>
      {subtitle ? <p className="text-xs text-slate-500 dark:text-slate-300 mt-1">{subtitle}</p> : null}
      <div className="mt-4">{children}</div>
    </div>
  );
}

function Field({ label, children, full }: { label: string; children: React.ReactNode; full?: boolean }) {
  return (
    <div className={full ? 'md:col-span-2' : ''}>
      <label className="text-xs font-semibold text-slate-600 dark:text-slate-300">{label}</label>
      <div className="mt-1">{children}</div>
    </div>
  );
}

function Row({ label, value, strong }: { label: string; value: string; strong?: boolean }) {
  return (
    <div className="flex items-center justify-between gap-4">
      <div className="text-sm text-slate-700 dark:text-slate-200">{label}</div>
      <div className={`text-sm ${strong ? 'font-extrabold' : 'font-semibold'} text-slate-900 dark:text-slate-100`}>{value}</div>
    </div>
  );
}

function IncomeTable({ rows }: { rows: IncomeRow[] }) {
  const sorted = rows.slice().sort((a, b) => new Date(a.startIso).getTime() - new Date(b.startIso).getTime());

  return (
    <div className="mt-6 pc-card bg-white dark:bg-slate-950">
      <h2 className="font-bold text-slate-800 dark:text-slate-100">Citas del mes ({sorted.length})</h2>
      <p className="text-xs text-slate-500 dark:text-slate-300 mt-1">Para cuadrar entradas por calendario y ver pendientes.</p>

      <div className="mt-4 overflow-auto max-h-[520px]">
        <table className="min-w-full text-sm">
          <thead className="sticky top-0 bg-slate-50 dark:bg-slate-950 border-b border-slate-200 dark:border-slate-800">
            <tr>
              <th className="text-left px-3 py-2 font-bold text-slate-600 dark:text-slate-200 min-w-[220px]">Fecha</th>
              <th className="text-left px-3 py-2 font-bold text-slate-600 dark:text-slate-200 min-w-[220px]">Paciente</th>
              <th className="text-left px-3 py-2 font-bold text-slate-600 dark:text-slate-200 min-w-[160px]">Pago</th>
              <th className="text-left px-3 py-2 font-bold text-slate-600 dark:text-slate-200 min-w-[160px]">Valor</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
            {sorted.map((r) => {
              const d = new Date(r.startIso);
              const label = d.toLocaleString('es-CO', { year: 'numeric', month: 'short', day: '2-digit', hour: '2-digit', minute: '2-digit' });
              return (
                <tr key={r.id} className="hover:bg-slate-50 dark:hover:bg-slate-950/50">
                  <td className="px-3 py-2 text-slate-700 dark:text-slate-200">{label}</td>
                  <td className="px-3 py-2 text-slate-700 dark:text-slate-200">{r.patientName ?? 'Paciente'}</td>
                  <td className="px-3 py-2">
                    <span
                      className={`text-xs font-semibold px-2 py-1 rounded-full ${
                        r.paymentStatus === 'paid'
                          ? 'bg-emerald-50 dark:bg-emerald-950/30 text-emerald-700 dark:text-emerald-200'
                          : 'bg-amber-50 dark:bg-amber-950/30 text-amber-800 dark:text-amber-200'
                      }`}
                    >
                      {r.paymentStatus === 'paid' ? 'Pagado' : 'Pendiente'}
                    </span>
                  </td>
                  <td className="px-3 py-2 font-semibold text-slate-800 dark:text-slate-100">{fmtCOP(r.feeCents ?? 0)}</td>
                </tr>
              );
            })}
            {!sorted.length && (
              <tr><td className="px-3 py-8 text-slate-500 dark:text-slate-300" colSpan={4}>No hay citas en este mes.</td></tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
